--#SET TERMINATOR ;

-- =============================================
-- SaveToDB Framework for IBM DB2
-- Version 10.8, January 9, 2023
--
-- Copyright 2012-2023 Gartle LLC
--
-- License: MIT
-- =============================================

DROP PROCEDURE XLS.XL_ACTIONS_SET_ROLE_PERMISSIONS;
DROP PROCEDURE XLS.XL_ACTIONS_SET_EXTENDED_ROLE_PERMISSIONS;
DROP PROCEDURE XLS.XL_ACTIONS_REVOKE_EXTENDED_ROLE_PERMISSIONS;
DROP PROCEDURE XLS.XL_UPDATE_TABLE_FORMAT;

DROP VIEW XLS.VIEW_COLUMNS;
DROP VIEW XLS.VIEW_FORMATS;
DROP VIEW XLS.VIEW_HANDLERS;
DROP VIEW XLS.VIEW_OBJECTS;
DROP VIEW XLS.VIEW_QUERIES;
DROP VIEW XLS.VIEW_TRANSLATIONS;
DROP VIEW XLS.VIEW_WORKBOOKS;
DROP VIEW XLS.QUERIES;
DROP VIEW XLS.USERS;

DROP INDEX  XLS.IX_COLUMNS;
DROP INDEX  XLS.IX_FORMATS;
DROP INDEX  XLS.IX_HANDLERS;
DROP INDEX  XLS.IX_OBJECTS;
DROP INDEX  XLS.IX_TRANSLATIONS;
DROP INDEX  XLS.IX_WORKBOOKS;

DROP TABLE  XLS.COLUMNS;
DROP TABLE  XLS.FORMATS;
DROP TABLE  XLS.HANDLERS;
DROP TABLE  XLS.OBJECTS;
DROP TABLE  XLS.TRANSLATIONS;
DROP TABLE  XLS.WORKBOOKS;

DROP ROLE   XLS_USERS;
DROP ROLE   XLS_FORMATS;
DROP ROLE   XLS_DEVELOPERS;

DROP SCHEMA XLS RESTRICT;

echo SaveToDB Framework removed
